Add EC-Shop
EC-Nordbund/EC-Website pull request #108
Opened 2021-10-22 13:49 UTC by tobikrs

noch nicht mergen, da die Designs noch vom AKÖ bearbeitet werden!

2021-10-22 13:53 UTC, mathe42 requested changes

2021-10-22 13:53 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
1. shopname bitte nicht dynamisch
2. Können wir die Datei mit ins Bundle kriegen? Oder ist da richtig dynamic hinter?

2021-10-22 13:55 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
Schau dir die Datei mal an die ist recht klein... Ich würde das lieber direkt eingebunden haben...

2021-10-22 14:01 UTC, tobikrs commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
Wenn spreadshirt dann etwas ändert bekommen wir es erst mit wenn jemand uns ne Mail schreibt, dass der Shop nicht geht :/

2021-10-22 14:06 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
Mach das wie folgt:

Im Mounted Hook:
```
await import('https://nordbund.myspreadshop.net/js/shopclient.nocache.js')
```

2021-10-22 14:06 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
Ich habe ein Problem mit script dynamisch hinzufügen

2021-10-23 13:11 UTC, tobikrs commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
> Mach das wie folgt:
> 
> Im Mounted Hook:
> 
> ```
> await import('https://nordbund.myspreadshop.net/js/shopclient.nocache.js')
> ```

... so einfach geht das glaube ich nicht. Dafür müsste man das script als dependency zur Verfügung stellen.

2021-10-23 13:14 UTC, tobikrs commented on components/ecSpreadshirtShop.vue
> +      :src='`https://${shopName}.myspreadshop.net/js/shopclient.nocache.js`'
Schau dir bitte mal an wie ich es aktuell gelöst habe.
https://github.com/EC-Nordbund/EC-Website/blob/66093b5e3b9c527287530467aa45557c1327b11e/components/ecSpreadshirtShop.vue#L45-L54

Man könnte falls nötig noch einen `callback` für wenn das script geladen ist hinzufügen.

2021-10-23 14:21 UTC, mathe42 requested changes
Sieht ganz gut aus (nicht selber getestet)

2021-10-23 14:21 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +    onMounted(() => {
Mit in useMeta funktion packen...

2021-10-23 14:21 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +    onMounted(() => {
Mit `process.browser` prüfen ob im client. Serverseitig in jedem Fall das script hinzufügen

2021-10-23 14:21 UTC, mathe42 commented on components/ecSpreadshirtShop.vue
> +    onMounted(() => {
Und prefix zu real url machen ohne template syntax.

2021-10-23 14:21 UTC, mathe42 commented on pages/shop.vue
> +<style>
Wenn style leer ihn löschen...

2021-11-06 20:46 UTC, merged