add filter for veranstaltungen
EC-Nordbund/EC-Website pull request #110
Opened 2021-10-23 03:37 UTC by tobikrs

2021-10-23 14:27 UTC, mathe42 requested changes

2021-10-23 14:27 UTC, mathe42 commented on pages/veranstaltungen/index.vue
> +    function filter(veranstaltung: any, scope?: Scope, tags?: string[], keyword?: string) {
Geht glaube ich besser wenn du in dem swich statement das gegenteil übreprüfst und dann direkt returnst. Effizienter (das ist hier gleube ich nicht wichtig) aber besser lesbar.

2021-10-23 14:27 UTC, mathe42 commented on pages/veranstaltungen/index.vue
> +      const tags = [...new Set(vData.value.flatMap((v: any) => v.tags))]
Warum ein Set draus machen um das wieder zu destructuren?
vData,value.flatMap(...) ist ja schon ein array.

2021-10-26 18:48 UTC, tobikrs commented on pages/veranstaltungen/index.vue
> +      const tags = [...new Set(vData.value.flatMap((v: any) => v.tags))]
das Set soll die doppelten Elemente entfernen

2021-10-26 20:09 UTC, mathe42 commented on pages/veranstaltungen/index.vue
> +      const tags = [...new Set(vData.value.flatMap((v: any) => v.tags))]
`array.filter((v,i,t)=>t.indexOf(v)===i)` macht das auch... Ist vermutlich effizienter...

2021-10-26 20:09 UTC, mathe42 commented on pages/veranstaltungen/index.vue
> +      const tags = [...new Set(vData.value.flatMap((v: any) => v.tags))]
Kann aber auch so bleiben. Nicht sicher welcher code klarer ist.... Wenn es so bleiben soll code-comment einfügen

2021-11-06 15:10 UTC, mathe42 approved these changes

2021-11-06 20:27 UTC, merged