make website static
EC-Nordbund/EC-Website pull request #179
Opened 2022-02-04 18:18 UTC by mathe42

2022-03-02 10:42 UTC, mathe42 commented
LAST WORKING COMMIT [02f2ef5](https://github.com/EC-Nordbund/EC-Website/pull/179/commits/02f2e5fbca36a727f7672599f62e38b946c69263)

2022-04-06 11:17 UTC, tobikrs requested changes

2022-04-06 11:17 UTC, tobikrs commented on .github/workflows/ci.yml
> +          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.event.client_payload.branch }}'
Wird nicht verwendet, kann raus

2022-04-06 11:17 UTC, tobikrs commented on .github/workflows/lighthouse.yml
> +          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.event.client_payload.branch }}'
hat hier nicht zu suchen, muss raus

2022-04-06 11:23 UTC, mathe42 commented on .github/workflows/ci.yml
> +          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.event.client_payload.branch }}'
Done

2022-04-06 11:24 UTC, mathe42 commented on .github/workflows/lighthouse.yml
> +          dest: 'deployer@ec-nordbund.de:/samba_share/preview.ec-nordbund.de/${{ github.event.client_payload.branch }}'
Done

2022-04-06 13:53 UTC, merged