change to yarn v2
EC-Nordbund/EC-Website pull request #71
Opened 2021-03-12 16:45 UTC by mathe42

2021-03-16 18:51 UTC, mathe42 commented
@tobikrs ist fertig. Musste nur vuetify updaten was aktuell den Datepicker kaputt macht.

Gibt noch 2-3 Problemchen im dev aber das kriege ich in den griff...

2021-03-17 14:49 UTC, mathe42 commented
ToDo's:
- [ ] fix `yarn dev`
- [ ] fix date picker (auch in #72 ?)

2021-03-18 14:43 UTC, tobikrs requested changes
der `test` file kann auch wieder weg, right?

2021-03-18 14:43 UTC, tobikrs commented on .gitignore
> -.vscode
`launch.json` sollten wir denke ich nicht teilen. Mein Vorschlag:

```
.vscode/*
!.vscode/extensions.json
!.vscode/settings.json
*.code-workspace
```

2021-03-18 14:43 UTC, tobikrs commented on .vscode/launch.json
> +}
bitte raus nehmen, kann jeder für sich so configurieren wie er mag.

2021-03-18 14:43 UTC, tobikrs commented on .yarn/build-state.yml
> +  c082b60c39e66821df7b1289cbb645e6f4e883f6041ab155d6a8c70f27a56c5a708ff89c8e39ece73a030932f33913dbf61c8df077ec4318f3ed4e956b798427
Müssen wir das mit versionieren? Es wird doch bei jedem build überschrieben... oder ist das gerade notwendig für yarnv2?

2021-03-18 14:43 UTC, tobikrs commented on helpers/fetch.ts
> +
`console.log`s müssen noch raus

2021-03-18 14:54 UTC, mathe42 commented on helpers/fetch.ts
> +
Done

2021-03-18 14:56 UTC, tobikrs requested changes
mit dem SharePoint Ordner müsste doch auch die Download Seite lokal funktionieren, oder?

Wenn ich auf einen Ordner oder Datei klicke, kommt:
```
[Vue warn]: Property or method "file" is not defined on the instance but referenced during render. ...
TypeError: _vm.file is undefined
```

2021-03-18 14:57 UTC, mathe42 commented
Schau ich mir an...

2021-03-18 15:16 UTC, mathe42 commented
Geht wieder außer die icons :D

2021-03-18 15:44 UTC, mathe42 commented
@tobikrs Bitte ignoriere die icons ist ein bug in so einer komischen bibliotherk @ec-nordbund/vuetify-icon-injector muss da mal mit den Entwickler darüber informieren ;)

2021-03-18 16:20 UTC, mathe42 commented
@tobikrs So jetzt müsste alles gehen!

2021-03-18 19:48 UTC, merged