Seite für Kriesenintervention
EC-Nordbund/EC-Website pull request #8
Opened 2020-12-15 21:14 UTC by tobikrs

so gut wie fertig...

missing:
- [ ] Test (funktioniert das Downloaden? – Wie local testen?)
- [ ] Review durch Thomas
- [ ] Nach Review von Thomas: Feedback von Dortje und Jutta...

2020-12-15 21:19 UTC, mathe42 requested changes

2020-12-15 21:19 UTC, mathe42 commented on pages/krisenintervention.vue
> +      async () => await $content('krisenintervention/explanation').fetch<any>()
await bei return wegnehmen ist nicht benötigt. Hier also auch das async weg.

2020-12-15 21:19 UTC, mathe42 commented on pages/krisenintervention.vue
> +      async () => await $content('krisenintervention/explanation').fetch<any>()
bei fileData genau so

2020-12-15 21:19 UTC, mathe42 commented on pages/krisenintervention.vue
> +        console.log(fileData.value.folders?.Krisenintervention)
Aus ? ein ! machen. Wir wissen es existiert wenn es nicht existiert ist das ein fehler und er soll einen Fehler throw

2020-12-15 21:19 UTC, mathe42 commented on pages/krisenintervention.vue
> +          v-list-item(v-for="file in data.files" :key="'file_' + file.filename"  :href="`${file.filename}`").px-1
sieht ok aus.

2020-12-15 21:19 UTC, mathe42 commented
Review nicht vollständig nur das was ich direkt gesehen habe.

2020-12-15 21:26 UTC, mathe42 commented
Und bitte deinen commit auf main bzw neuen branch ausführen der hier ist schon gemergt...

2020-12-15 21:29 UTC, mathe42 commented on pages/downloads/_.vue
> +      v-list-item(v-for="el in data.files" :key="$route.fullpath + el.filename" :to="`${el.filename}`" two-line download link)
Wieso?

2020-12-15 21:29 UTC, mathe42 commented on pages/krisenintervention.vue
> +          v-col(cols="12").py-0
Warum v-col dort einbauen?

2020-12-15 21:35 UTC, tobikrs commented on pages/krisenintervention.vue
> +        console.log(fileData.value.folders?.Krisenintervention)
Runtime Exceptions sind dooof -.-

2020-12-15 21:37 UTC, tobikrs commented on pages/downloads/_.vue
> +      v-list-item(v-for="el in data.files" :key="$route.fullpath + el.filename" :to="`${el.filename}`" two-line download link)
Ausversehen mit commited

2020-12-15 21:41 UTC, mathe42 commented on pages/krisenintervention.vue
> +        console.log(fileData.value.folders?.Krisenintervention)
Ok akzeptiert... Würde halt 5 Bytes oder so sparen😁

2020-12-15 21:49 UTC, tobikrs commented on pages/krisenintervention.vue
> +          v-col(cols="12").py-0
Hat ohne nicht gut für Desktop UND mobile Ansicht geklappt, wenn mans nun wegnimmt wird der inhalt der v-card nicht mehr angezeigt...

2020-12-15 22:07 UTC, mathe42 approved these changes

2020-12-17 08:57 UTC, mathe42 commented
Zum testen. Local ankliecken und dann localhost durch ec-nordbund.de ersetzen. Wenn es dann geht sollte es auch produktiv gehen.

2021-01-12 12:17 UTC, merged